export const OPEN_AUTH_MODAL = 'OPEN_AUTH_MODAL';
export const USER_DETAILS = "USER_DETAILS";
export const IS_AUTHENTICATED = "IS_AUTHENTICATED";
export const CHANGE_INDEX = "CHANGE_INDEX";
export const ERROR_HANDLER = "ERROR_HANDLER";
export const STEPPER_DECREMENT = "STEPPER_DECREMENT";
export const STEPPER_INCREMENT = "STEPPER_INCREMENT";